In [1]:
import pandas as pd
import csv
from pathlib import Path
import json
import numpy as np
from datetime import datetime
import time
import os
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import plotly.graph_objects as go

In [2]:
root_path = ###deleted for security reasons###
out_path = ###deleted for security reasons###
pic_path = ###deleted for security reasons###

In [3]:
covid_owd_statistics = pd.read_csv(root_path/'covid_owd_statistics.csv')

In [4]:
covid_owd_statistics = pd.read_csv(root_path/'covid_owd_statistics.csv', low_memory=False)

In [12]:
covid_owd_statistics

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,TWN,Asia,Taiwan,2022-03-19,21784.0,126.0,79.857,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
1,TWN,Asia,Taiwan,2022-03-20,21905.0,121.0,88.143,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
2,TWN,Asia,Taiwan,2022-03-21,22003.0,98.0,91.429,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
3,TWN,Asia,Taiwan,2022-03-22,22091.0,88.0,98.429,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
4,TWN,Asia,Taiwan,2022-03-23,22188.0,97.0,99.429,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
5,TWN,Asia,Taiwan,2022-03-24,22327.0,139.0,106.286,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
6,TWN,Asia,Taiwan,2022-03-25,22463.0,136.0,115.000,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
7,TWN,Asia,Taiwan,2022-03-26,22566.0,103.0,111.714,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
8,TWN,Asia,Taiwan,2022-03-27,22769.0,203.0,123.429,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
9,TWN,Asia,Taiwan,2022-03-28,22896.0,127.0,127.571,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
10,TWN,Asia,Taiwan,2022-03-29,22992.0,96.0,128.714,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
11,TWN,Asia,Taiwan,2022-03-30,23155.0,163.0,138.143,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
12,TWN,Asia,Taiwan,2022-03-31,23394.0,239.0,152.429,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,-3474.3,-0.85,1.29,-145.642374
13,TWN,Asia,Taiwan,2022-04-01,23629.0,235.0,166.571,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
14,TWN,Asia,Taiwan,2022-04-02,24033.0,404.0,209.571,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
15,TWN,Asia,Taiwan,2022-04-03,24313.0,280.0,220.571,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
16,TWN,Asia,Taiwan,2022-04-04,24588.0,275.0,241.714,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
17,TWN,Asia,Taiwan,2022-04-05,24866.0,278.0,267.714,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
18,TWN,Asia,Taiwan,2022-04-06,25225.0,359.0,295.714,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
19,TWN,Asia,Taiwan,2022-04-07,25756.0,531.0,337.429,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
20,TWN,Asia,Taiwan,2022-04-08,26263.0,507.0,376.286,853.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
21,TWN,Asia,Taiwan,2022-04-09,26836.0,573.0,400.429,854.0,1.0,0.143,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
22,TWN,Asia,Taiwan,2022-04-10,27410.0,574.0,442.429,854.0,0.0,0.143,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
23,TWN,Asia,Taiwan,2022-04-11,28040.0,630.0,493.143,854.0,0.0,0.143,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
24,TWN,Asia,Taiwan,2022-04-12,28666.0,626.0,542.857,854.0,0.0,0.143,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
25,TWN,Asia,Taiwan,2022-04-13,29593.0,927.0,624.000,854.0,0.0,0.143,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
26,TWN,Asia,Taiwan,2022-04-14,30574.0,981.0,688.286,854.0,0.0,0.143,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
27,TWN,Asia,Taiwan,2022-04-15,31857.0,1283.0,799.143,854.0,0.0,0.143,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
28,TWN,Asia,Taiwan,2022-04-16,33205.0,1348.0,909.857,854.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
29,TWN,Asia,Taiwan,2022-04-17,34507.0,1302.0,1013.857,854.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
30,TWN,Asia,Taiwan,2022-04-18,35983.0,1476.0,1134.714,854.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
31,TWN,Asia,Taiwan,2022-04-19,37710.0,1727.0,1292.000,854.0,0.0,0.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
32,TWN,Asia,Taiwan,2022-04-20,40186.0,2476.0,1513.286,856.0,2.0,0.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
33,TWN,Asia,Taiwan,2022-04-21,43243.0,3057.0,1809.857,856.0,0.0,0.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
34,TWN,Asia,Taiwan,2022-04-22,47100.0,3857.0,2177.571,856.0,0.0,0.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
35,TWN,Asia,Taiwan,2022-04-23,51298.0,4198.0,2584.714,856.0,0.0,0.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
36,TWN,Asia,Taiwan,2022-04-24,56468.0,5170.0,3137.286,856.0,0.0,0.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
37,TWN,Asia,Taiwan,2022-04-25,61686.0,5218.0,3671.857,856.0,0.0,0.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
38,TWN,Asia,Taiwan,2022-04-26,68022.0,6336.0,4330.286,856.0,0.0,0.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
39,TWN,Asia,Taiwan,2022-04-27,76938.0,8916.0,5250.286,858.0,2.0,0.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
40,TWN,Asia,Taiwan,2022-04-28,88446.0,11508.0,6457.571,860.0,2.0,0.571,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
41,TWN,Asia,Taiwan,2022-04-29,100753.0,12307.0,7664.714,862.0,2.0,0.857,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
42,TWN,Asia,Taiwan,2022-04-30,115883.0,15130.0,9226.429,865.0,3.0,1.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
43,TWN,Asia,Taiwan,2022-05-01,132955.0,17072.0,10926.714,868.0,3.0,1.714,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
44,TWN,Asia,Taiwan,2022-05-02,132955.0,0.0,10181.286,868.0,0.0,1.714,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
45,TWN,Asia,Taiwan,2022-05-03,173942.0,40987.0,15131.429,876.0,8.0,2.857,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
46,TWN,Asia,Taiwan,2022-05-04,202418.0,28476.0,17925.714,881.0,5.0,3.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
47,TWN,Asia,Taiwan,2022-05-05,232402.0,29984.0,20565.143,886.0,5.0,3.714,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
48,TWN,Asia,Taiwan,2022-05-06,268569.0,36167.0,23973.714,896.0,10.0,4.857,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
49,TWN,Asia,Taiwan,2022-05-07,268569.0,0.0,21812.286,896.0,0.0,4.429,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
50,TWN,Asia,Taiwan,2022-05-08,268569.0,0.0,19373.429,896.0,0.0,4.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
51,TWN,Asia,Taiwan,2022-05-09,397504.0,128935.0,37792.714,931.0,35.0,9.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
52,TWN,Asia,Taiwan,2022-05-10,448323.0,50819.0,39197.286,943.0,12.0,9.571,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
53,TWN,Asia,Taiwan,2022-05-11,505455.0,57132.0,43291.000,951.0,8.0,10.000,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
54,TWN,Asia,Taiwan,2022-05-12,570870.0,65415.0,48352.571,968.0,17.0,11.714,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN
55,TWN,Asia,Taiwan,2022-05-13,570870.0,0.0,43185.857,968.0,0.0,10.286,...,NaN,NaN,NaN,NaN,80.46,NaN,NaN,NaN,NaN,NaN

In [6]:
taiwan = covid_owd_statistics[['location', 'date', 'new_cases']]

In [7]:
taiwan[taiwan['new_cases']==0]

   location        date  new_cases
44   Taiwan  2022-05-02        0.0
49   Taiwan  2022-05-07        0.0
50   Taiwan  2022-05-08        0.0
55   Taiwan  2022-05-13        0.0

In [13]:
taiwan.loc[44, 'new_cases'] = 17858
taiwan.loc[45, 'new_cases'] = 23139
taiwan.loc[49, 'new_cases'] = 46536
taiwan.loc[50, 'new_cases'] = 44361
taiwan.loc[51, 'new_cases'] = 40304
taiwan.loc[55, 'new_cases'] = 65011

/opt/homebrew/lib/python3.9/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [14]:
taiwan.to_csv(root_path/'tw_covid_daily_new_cases.csv', index=False)